spring.application.name=backend
server.port=8081
debug=false

# MongoDB
app.mongo.uri=mongodb://localhost:27017
app.mongo.database=ebsa_medical
spring.data.mongodb.auto-index-creation=true

# JWT (1 hora)
app.jwt.secret=CAMBIA_ESTE_SECRET_POR_UNO_LARGO_DE_64_CARACTERES_MINIMO_1234567890
app.jwt.expiration-minutes=60

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,https://sstalturas.ebsa.com.co

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO

# Envío automático de correos
app.email.auto-send-enabled=true

# URL del frontend usada dentro de los correos
app.frontend.base-url=https://sstalturas.ebsa.com.co

# Correos fallback para el aprobador.
# Normalmente quedan vacíos porque el correo real se guarda desde la app en MongoDB.
app.email.approver-to=
app.email.approver-cc=

# Configuración del servidor SMTP empresarial
spring.mail.host=10.1.200.20
spring.mail.port=25
spring.mail.username=sstalturas@ebsa.com.co
spring.mail.password=Anubis494*

spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Copias por defecto separadas por coma.
# Respaldo técnico. La configuración principal de talento humano, nómina y coordinadores
# se guarda desde la app en MongoDB.
app.email.default-cc=

# Firma del correo


# Tamaño máximo permitido para PDFs individuales
spring.servlet.multipart.max-file-size=150MB

# Tamaño máximo permitido para carga masiva
spring.servlet.multipart.max-request-size=500MB

# Permitir que Tomcat reciba solicitudes multipart grandes
server.tomcat.max-swallow-size=500MB
server.tomcat.max-http-form-post-size=500MB

# Valores por defecto para archivo plano Ministerio
app.reports.ministry.default-country=COLOMBIA
app.reports.ministry.default-education-level=
app.reports.ministry.default-sector=Sector minero y energetico
app.reports.ministry.default-company=Empresa de energia de Boyaca
app.reports.ministry.default-arl=Axa colpatria seguros de vida
