spring.application.name=backend
server.port=8080

# MongoDB
app.mongo.uri=mongodb://localhost:27017
app.mongo.database=ebsa_medical

# JWT (1 hora)
app.jwt.secret=CAMBIA_ESTE_SECRET_POR_UNO_LARGO_DE_64_CARACTERES_MINIMO_1234567890
app.jwt.expiration-minutes=60

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

logging.level.org.springframework.security=INFO

# Envío automático de correos
app.email.auto-send-enabled=true

# Configuraci n del servidor SMTP
spring.mail.host=10.1.200.20
spring.mail.port=25
spring.mail.username=SIRED@ebsa.com.co
spring.mail.password=Sired_2025

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Copias por defecto separadas por coma.
# Aquí van talento humano, SST u otros correos fijos.
app.email.default-cc=
#talentohumano@ebsa.com.co,seguridadysalud@ebsa.com.co

# Firma del correo
app.email.signature-name=Hector Hernan Contreras Pena
app.email.signature-role=Director de Seguridad, Salud y Ambiente
app.email.signature-phone=Tel: +57 (8) 740 5000 Ext: 9508 | +57 315 313 6988
app.email.signature-address=Carrera 10 N° 15 - 87 Tunja, Boyacá, Colombia

# Tamaño máximo permitido para PDFs individuales
spring.servlet.multipart.max-file-size=50MB

# Tamaño máximo permitido para carga masiva
spring.servlet.multipart.max-request-size=300MB

# Permitir que Tomcat reciba solicitudes multipart grandes
server.tomcat.max-swallow-size=300MB
server.tomcat.max-http-form-post-size=300MB
